import Link from 'next/link';

export const metadata = {
    title: 'Terms of Service – Sharpen.ai',
    description: 'Terms of Service for Sharpen.ai, the AI-powered interview coaching platform.',
};

const LAST_UPDATED = 'March 25, 2025';
const CONTACT_EMAIL = 'legal@sharpen.ai';

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-[#FDFCFB] dark:bg-[#0B1221] transition-colors duration-500">
            <div className="max-w-3xl mx-auto px-6 py-20">

                {/* Header */}
                <div className="mb-16">
                    <Link href="/login" className="text-[10px] font-bold text-gray-400 dark:text-gray-600 uppercase tracking-[0.2em] hover:text-brand-purple transition-colors mb-10 inline-block">
                        ← Back to Sharpen.ai
                    </Link>
                    <span className="text-[10px] font-bold text-brand-purple uppercase tracking-[0.3em] mb-4 block">Legal</span>
                    <h1 className="text-5xl font-bold text-gray-900 dark:text-white tracking-tight leading-[1.1] mb-6 font-serif italic">Terms of Service</h1>
                    <p className="text-gray-400 dark:text-gray-600 text-sm font-medium">Last updated: {LAST_UPDATED}</p>
                </div>

                {/* Content */}
                <div className="prose prose-gray max-w-none space-y-12">

                    <Section title="1. Acceptance of Terms">
                        <p>By accessing or using Sharpen.ai ("the Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, please do not use the Service.</p>
                        <p>We may update these Terms from time to time. Continued use of the Service after changes constitutes acceptance of the revised Terms.</p>
                    </Section>

                    <Section title="2. Description of Service">
                        <p>Sharpen.ai is an AI-powered interview coaching platform that helps candidates prepare for technical and behavioral interviews. The Service includes:</p>
                        <ul>
                            <li>AI analysis of interview recordings and reconstructed sessions</li>
                            <li>Performance metrics, feedback, and coaching recommendations</li>
                            <li>Practice simulations and learning modules</li>
                            <li>Personalized improvement roadmaps</li>
                        </ul>
                    </Section>

                    <Section title="3. Eligibility">
                        <p>You must be at least 16 years old to use Sharpen.ai. By using the Service, you represent that you meet this requirement and that the information you provide is accurate and complete.</p>
                    </Section>

                    <Section title="4. Account and Authentication">
                        <p>We use Google OAuth for authentication. By signing in, you grant Sharpen.ai access to your basic Google profile information (name, email, and profile picture). We do not receive or store your Google password.</p>
                        <p>You are responsible for all activity that occurs under your account. Notify us immediately at <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a> if you suspect unauthorized access.</p>
                    </Section>

                    <Section title="5. User Content">
                        <p>You retain ownership of all content you submit, including interview recordings, text responses, and profile information ("User Content").</p>
                        <p>By submitting User Content, you grant Sharpen.ai a limited, non-exclusive, royalty-free license to process, analyze, and use that content solely to provide and improve the Service. We do not sell your User Content to third parties.</p>
                        <p>You agree not to submit content that is unlawful, defamatory, harassing, or infringes any third-party rights.</p>
                    </Section>

                    <Section title="6. AI-Generated Analysis">
                        <p>The feedback, scores, and recommendations generated by Sharpen.ai are produced by artificial intelligence and are intended for educational and coaching purposes only. They do not constitute professional career, legal, or employment advice.</p>
                        <p>AI analysis may be inaccurate or incomplete. You should use your own judgment when acting on any AI-generated feedback.</p>
                    </Section>

                    <Section title="7. Prohibited Conduct">
                        <p>You agree not to:</p>
                        <ul>
                            <li>Reverse-engineer, scrape, or copy any part of the Service</li>
                            <li>Use the Service to cheat in actual interviews or misrepresent your skills to employers</li>
                            <li>Attempt to circumvent usage limits or access controls</li>
                            <li>Upload malicious files or attempt to compromise our systems</li>
                            <li>Share your account credentials with others</li>
                        </ul>
                    </Section>

                    <Section title="8. Intellectual Property">
                        <p>The Sharpen.ai name, logo, platform design, and all software are the exclusive intellectual property of Sharpen.ai and its licensors. Nothing in these Terms grants you a right to use our trademarks or branding.</p>
                    </Section>

                    <Section title="9. Disclaimer of Warranties">
                        <p>THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR PRODUCE SPECIFIC RESULTS FOR YOUR CAREER GOALS.</p>
                    </Section>

                    <Section title="10. Limitation of Liability">
                        <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, SHARPEN.AI SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES ARISING FROM YOUR USE OF THE SERVICE, INCLUDING LOSS OF EMPLOYMENT OPPORTUNITIES OR CAREER OUTCOMES.</p>
                    </Section>

                    <Section title="11. Termination">
                        <p>We reserve the right to suspend or terminate your account at any time for violations of these Terms. You may delete your account at any time by contacting us at <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.</p>
                    </Section>

                    <Section title="12. Governing Law">
                        <p>These Terms are governed by applicable law. Any disputes shall be resolved through binding arbitration or the courts of the jurisdiction in which Sharpen.ai operates.</p>
                    </Section>

                    <Section title="13. Contact">
                        <p>For legal inquiries, contact us at: <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a></p>
                    </Section>

                </div>

                {/* Footer links */}
                <div className="mt-20 pt-10 border-t border-gray-100 dark:border-white/5 flex gap-8">
                    <Link href="/privacy" className="text-[10px] font-bold text-gray-400 hover:text-brand-purple transition-colors uppercase tracking-widest">Privacy Policy</Link>
                    <Link href="/login" className="text-[10px] font-bold text-gray-400 hover:text-brand-purple transition-colors uppercase tracking-widest">Back to App</Link>
                </div>

            </div>
        </div>
    );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
    return (
        <div className="bg-white dark:bg-[#0F172A]/40 border border-gray-100 dark:border-white/5 rounded-[2rem] p-10">
            <h2 className="text-lg font-bold text-gray-900 dark:text-white mb-6 tracking-tight">{title}</h2>
            <div className="space-y-4 text-gray-500 dark:text-gray-400 text-[15px] leading-relaxed font-medium [&_a]:text-brand-purple [&_a:hover]:underline [&_ul]:list-disc [&_ul]:pl-6 [&_ul]:space-y-2">
                {children}
            </div>
        </div>
    );
}
